"""rename restock created_at to restock_date and fix type

Revision ID: 554c471f9046
Revises: 8b449c9d71d1
Create Date: 2026-06-18 19:01:00.018256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '554c471f9046'
down_revision: Union[str, Sequence[str], None] = '8b449c9d71d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATE(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('restocks', sa.Column('restock_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('restocks', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restocks', sa.Column('created_at', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('restocks', 'restock_date')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
