"""add user_id to businesses

Revision ID: 70637aea56ab
Revises: 2b7c66bff1de
Create Date: 2026-06-16 01:55:39.214091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70637aea56ab'
down_revision: Union[str, Sequence[str], None] = '2b7c66bff1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'businesses', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='unique')
    op.drop_column('businesses', 'user_id')
    # ### end Alembic commands ###
