"""fix created_at server defaults

Revision ID: 8b449c9d71d1
Revises: 70637aea56ab
Create Date: 2026-06-16 03:12:09.809499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b449c9d71d1'
down_revision: Union[str, Sequence[str], None] = '70637aea56ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
 
    op.alter_column('businesses', 'created_at', server_default=sa.func.now())
    op.alter_column('restocks', 'created_at', server_default=sa.func.now())
    op.alter_column('orders', 'created_at', server_default=sa.func.now())   # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
 
    op.alter_column('businesses', 'created_at', server_default=None)
    op.alter_column('restocks', 'created_at', server_default=None)
    op.alter_column('orders', 'created_at', server_default=None)   # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
